services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init_schemas.sql:/docker-entrypoint-initdb.d/init_schemas.sql

  python:
    image: python
    build: image
    volumes:
      - ./data:/app/data
      - ./data/logs:/app/data/logs
    depends_on:
      - database

volumes:
  mysql-data:
  